In [6]:
pip install otter-grader

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://packagemanager.posit.co/pypi/latest/simple
Collecting otter-grader
  Using cached https://p3m.dev/pypi/latest/packages/otter-grader/aad08cba3653b203c4bce5b2b40df675811ec13735207f2deda8d128120fd24a/otter_grader-7.0.0-py3-none-any.whl (145 kB)
Requirement already satisfied: click<9.0.0,>=8.1.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (8.4.2)
Collecting dill>=0.3.0 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/dill/1e1ce33e978ae97fcfcff5638477032b801c46c7c65cf717f95fbc2248f79a9d/dill-0.4.1-py3-none-any.whl (120 kB)
Collecting fica>=0.4.1 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/fica/d5cb066cfdc67715f99efdbce2fdaeb0c92f67b5d2aaf0740397b984731de2d5/fica-0.4.1-py3-none-any.whl (13 kB)
Collecting ipylab<2.0.0,>=1.0.0 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/ipylab/a24c29aeb7d6d8b26c150794ef30c8d9ac2e387c47ea49f9afd8fa19dcd07b62/ipylab-1.1.0-py3-none-any.whl (101 kB)
Requirement already satisfied: ipython in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (9.16.1)
Collecting ipywidgets<9.0.0,>=8.1.5 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/ipywidgets/f2b8cbcaae10252b809fbe4d7470db75c09b769a32cbf816d20e5ca6d3c5a79d/ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Requirement already satisfied: jinja2<4.0,>=3.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (3.1.6)
Collecting jupytext<2.0.0,>=1.19.3 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/jupytext/af22351202171116b986fe1f4f9233a13ca4a85d5eec57a87900ed48521dbae4/jupytext-1.19.5-py3-none-any.whl (229 kB)
Collecting nbconvert>=6.0.0 (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbconvert/aa85c087b435e7bf1ffd03319f658e285f2b89eccab33bc1ba7025495ab3e7c8/nbconvert-7.17.1-py3-none-any.whl (261 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.9/261.9 kB 16.1 MB/s eta 0:00:00
Collecting nbformat>=5.0.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbformat/cc6698fa75f4fab8755ead786317815f13a6fee3b53311c0abb1a8b51d52f7ec/nbformat-5.11.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 8.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=2.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (2.3.3)
Collecting python-frontmatter<2.0.0,>=1.3.0 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/python-frontmatter/9f7dd9260bec99044219159a329f64f039087f9d1a2124c9442556f2fe6f82ec/python_frontmatter-1.3.0-py3-none-any.whl (10 kB)
Collecting python-on-whales<1.0.0,>=0.72.0 (from otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/python-on-whales/6d5f81f56d0f95fd311a7cce29a01a1a60841074e4936000dc5f2dc9a7ffafac/python_on_whales-0.81.0-py3-none-any.whl (119 kB)
Collecting pyyaml<7,>=6 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pyyaml/b8bb0864c5a28024fac8a632c443c87c5aa6f215c0b126c449ae1a150412f31d/pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (806 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 806.6/806.6 kB 48.7 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0,>=2.31 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from otter-grader) (2.34.2)
Collecting wrapt<2.0.0,>=1.16.0 (from otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/wrapt/b32888aad8b6e68f83a8fdccbf3165f5469702a7544472bdf41f582970ed3311/wrapt-1.17.3-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 kB 7.8 MB/s eta 0:00:00
Collecting docutils (from fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/docutils/25d013af9bf23bc1c7b2b093dff4208166c53a94786c9e447808335ef1185fea/docutils-0.23-py3-none-any.whl (634 kB)
Collecting sphinx (from fica>=0.4.1->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/sphinx/5bebc595a5e943ea248b99c13814c1c5e10b3ece718976824ffa7959ff95fffb/sphinx-9.0.4-py3-none-any.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 103.1 MB/s eta 0:00:0000:01
Requirement already satisfied: comm>=0.1.3 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipywidgets<9.0.0,>=8.1.5->otter-grader) (5.16.1)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets<9.0.0,>=8.1.5->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/widgetsnbextension/a31a8774885b96fe825462f5d6496166f0c7cae111195b6465c801d230eb5a4e/widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets<9.0.0,>=8.1.5->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/jupyterlab-widgets/40ac1e9955acf116c4d995d9bfa082d86ad9ec6d91c4f134827cf5e0a5eb75e0/jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (3.0.53)
Requirement already satisfied: psutil>=7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from ipython->otter-grader) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jinja2<4.0,>=3.1->otter-grader) (3.0.3)
Collecting markdown-it-py>=1.0 (from jupytext<2.0.0,>=1.19.3->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/markdown-it-py/9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a/markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 9.4 MB/s eta 0:00:00
Collecting mdit-py-plugins (from jupytext<2.0.0,>=1.19.3->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/mdit-py-plugins/214c82fb2ac524472ab6a5bcab1de80f73b50443e187f401bfd77efbc7c6481d/mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Requirement already satisfied: packaging in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jupytext<2.0.0,>=1.19.3->otter-grader) (26.3)
Collecting beautifulsoup4 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/beautifulsoup4/d6f88de62e1d4e38ecb1077eb9724cd0eff29d2a08ca16a401e9b9e93f117cf9/beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.9/109.9 kB 10.9 MB/s eta 0:00:00
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/bleach/4b6b6a54fff2e69a3dde9d21cc6301220bee3c3cb792187d11403fd795031081/bleach-6.4.0-py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.1/165.1 kB 15.5 MB/s eta 0:00:00
Collecting defusedxml (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/defusedxml/a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61/defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: jupyter-core>=4.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (5.9.1)
Collecting jupyterlab-pygments (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jupyterlab-pygments/841a89020971da1d8693f1a99997aefc5dc424bb1b251fd6322462a1b8842780/jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/mistune/ee015381e955e370962968befe1d729ab60fafb6a715ac6751763fbce38c8d4a/mistune-3.3.4-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.9/66.9 kB 6.2 MB/s eta 0:00:00
Collecting nbclient>=0.5.0 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/nbclient/ef7fa0d59d6e1d41103933d8a445a18d5de860ca6b613b87b8574accdb3c2895/nbclient-0.11.0-py3-none-any.whl (25 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pandocfilters/93be382804a9cdb0a7267585f157e5d1731bbe5545a85b268d6f5fe6232de2bc/pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting playwright (from nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/playwright/ad21bc07516b187965a7521c5cf0df0bd657b17482eaad74335272d35a2b07de/playwright-1.63.0-py3-none-manylinux1_x86_64.whl (48.2 MB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/fastjsonschema/0fb3915616adac85ccfdd737d26be1089845d2019819505b42d39888458f74d4/fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jsonschema/d489f15263b8d200f8387e64b4c3a75f06629559fb73deb8fdfb525f2dab50ce/jsonschema-4.26.0-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 9.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pandas>=2.0.0->otter-grader) (2026.3)
Collecting pydantic!=2.0.*,<3,>=2 (from python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pydantic/346a034f080da3755d8e9cb5e00e8b07de1d39e4f6e2c87d8ab7cafa0b269a73/pydantic-2.13.5-py3-none-any.whl (472 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.6/472.6 kB 34.5 MB/s eta 0:00:00
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from requests<3.0,>=2.31->otter-grader) (2026.7.22)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/webencodings/7fab6269c8bf237c657876b52058ccb182e861518d1c695c1a9aaa8c1c105d5b/webencodings-0.6.1-py3-none-any.whl (8.7 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/tinycss2/3415ba0f5839c062696996998176c4a3751d18b7edaaeeb658c9ce21ec150661/tinycss2-1.5.1-py3-none-any.whl (28 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jedi>=0.18.2->ipython->otter-grader) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader) (26.1.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/jsonschema-specifications/98802fee3a11ee76ecaca44429fda8a41bff98b00a0f2838151b113f210cc6fe/jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/referencing/381329a9f99628c9069361716891d34ad94af76e461dcb0335825aecc7692231/referencing-0.37.0-py3-none-any.whl (26 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat>=5.0.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/rpds-py/9c1255b302953c86a486b81d330d5ee1d5bd937691ce271b6be0ef0e299eaab7/rpds_py-2026.6.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (371 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.3/371.3 kB 28.5 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from jupyter-core>=4.7->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (4.11.3)
Collecting mdurl~=0.1 (from markdown-it-py>=1.0->jupytext<2.0.0,>=1.19.3->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/mdurl/84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: jupyter-client>=7.0.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from nbclient>=0.5.0->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader) (8.9.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from pexpect>4.6->ipython->otter-grader) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->otter-grader) (0.8.2)
Collecting annotated-types>=0.6.0 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/annotated-types/f072f4d804ea359e4eaf198b1af7a8b0943881a87f31bb764f8bf219bb9419e0/annotated_types-0.8.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.46.5 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/pydantic-core/49776eab08766a08dfff7012f8b422dcd7e25e43b316eedf0477c24fcfa84b7c/pydantic_core-2.46.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 76.1 MB/s eta 0:00:00
Collecting typing-inspection>=0.4.2 (from pydantic!=2.0.*,<3,>=2->python-on-whales<1.0.0,>=0.72.0->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/typing-inspection/65b8397ba37ccbce054456aaccddfc91e6e3083c92824df348d96ca832f3f147/typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->otter-grader) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (3.0.2)
Requirement already satisfied: pure_eval in /opt/miniforge3/envs/eds220/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython->otter-grader) (0.2.3)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert>=6.0.0->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/soupsieve/8596eb8967d744174820280fa62b4542a2e955bfaccca73ed8a13c6eb8e9b502/soupsieve-2.10-py3-none-any.whl (38 kB)
Collecting pyee<14,>=13 (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/pyee/af2f8fede4171ef667dfded53f96e2ed0d6e6bd7ee3bb46437f77e3b57689228/pyee-13.0.1-py3-none-any.whl (15 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright->nbconvert[webpdf]>=6.0.0; sys_platform != "emscripten" and sys_platform != "wasi"->otter-grader)
  Downloading https://p3m.dev/pypi/latest/packages/greenlet/1c20ea32a73d17b9b60e3371240e17b0068120c98a5ec01a224a7dd8c89733ba/greenlet-3.5.6-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (624 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.4/624.4 kB 42.2 MB/s eta 0:00:00
Collecting sphinxcontrib-applehelp>=1.0.7 (from sphinx->fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/sphinxcontrib-applehelp/4cd3f0ec4ac5dd9c17ec65e9ab272c9b867ea77425228e68ecf08d6b28ddbdb5/sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
Collecting sphinxcontrib-devhelp>=1.0.6 (from sphinx->fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/sphinxcontrib-devhelp/aefb8b83854e4b0998877524d1029fd3e6879210422ee3780459e28a1f03a8a2/sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.6 (from sphinx->fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/sphinxcontrib-htmlhelp/166759820b47002d22914d64a075ce08f4c46818e17cfc9470a9786b759b19f8/sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Collecting sphinxcontrib-jsmath>=1.0.1 (from sphinx->fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/sphinxcontrib-jsmath/2ec2eaebfb78f3f2078e73666b1415417a116cc848b72e5172e596c871103178/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-qthelp>=1.0.6 (from sphinx->fica>=0.4.1->otter-grader)
  Using cached https://p3m.dev/pypi/latest/packages/sphinxcontrib-qthelp/b18a828cdba941ccd6ee8445dbe72ffa3ef8cbe7505d8cd1fa0d42d3f2d5f3eb/sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)

In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/RachelMGitH/eds220-hwk1.git]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

The dataset contains coral reef locations, number of coral taxa, and climate change, water quality, human resource management and extraction variables for reef cells in The Western Indian Ocean faunal provience, averaged over the 1998-2022 sampling period.  

Tim McClanahan. (2023). Western Indian Ocean Coral Diversity. Knowledge Network for Biocomplexity. doi:10.5063/F1K35S3H.

The archive can be accessed via the following link [https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H]()

Date of access: October 4, 2026

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [2]:
import pandas as pd
coral_div = pd.read_csv('data/coral_data.csv')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [13]:
# Determine number of rows and columns
rows = coral_div.shape[0] #or len(coral_div)
columns = coral_div.shape[1]

In [14]:
grader.check("q3_a")

q3_a results: All test cases passed!

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [18]:
# Extract column names
coral_div_columns = coral_div.columns

In [19]:
grader.check("q3_b")

q3_b results: All test cases passed!

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [32]:
# Check dtypes of columns
coral_div_types = coral_div.dtypes

In [21]:
grader.check("q3_c")

q3_c results: All test cases passed!

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [25]:
# Update pandas option to view all columns
# Then, display first 8 rows
pd.set_option("display.max_columns", None)
first_8_rows = coral_div.head(8)

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,41,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.592692,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,49,0.021358,54.935499,0.001744,4.7540,2.857747,35.106329,0,2.645199,1150.677856,1.783333,0.333333,30.265219,-0.795494,27.525,0.656533,3224.024414,0.561659,0.10500,0.512126,19.634828,8.2185,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [26]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,41,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.592692,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,49,0.021358,54.935499,0.001744,4.7540,2.857747,35.106329,0,2.645199,1150.677856,1.783333,0.333333,30.265219,-0.795494,27.525,0.656533,3224.024414,0.561659,0.10500,0.512126,19.634828,8.2185,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [27]:
grader.check("q3_d")

q3_d results: All test cases passed!

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [30]:
# Check number of unqiue values in each column
unique_values = coral_div.nunique()

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

The data type `int64` denotes numerical data composed of only integers, while `float64` denotes numerical data that may include decimal values.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

The output of `coral_div['Country']` is a pandas.Series with the contents of the 'Country' column from coral_div.

The output of `coral_div['Country'].unique()` is a numpy array with each distinct value from the 'Country' column in coral_div listed only once. In other words, the output displays all the countries where coral reefs in the data are located.

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [48]:
# Check number of unique values in Observer column
unique_observers = coral_div['Observer'].nunique()

In [47]:
grader.check("q6")

q6 results: All test cases passed!

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

`coral_div['Coralcover']>= 50` is a pandas.Series of boolean values indicating whether each entry in the 'Coralcover' column meets the crietria of being greater than or equal to 50.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

`coral_div[coral_div['Coralcover'] >= 50]` selects all rows in the coral_div dataframe in which the 'Coralcover' column contains a value greater than or equal to 50. In other words, it selects all rows that return a 'True' value for `coral_div['Coralcover']>= 50`.

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [81]:
# Select rows with a coral cover of 30% in Tanzania
coral_cover = coral_div[ (coral_div['Coralcover'] == 30) & (coral_div['Country'] == 'Tanzania')]

In [72]:
# View the dataframe
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,30,0.015676,52.992001,0.037043,4.7580,5.885771,35.099083,1156,1.507334,958.495666,0.950000,0.550000,30.656667,-0.940944,27.3625,0.225574,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,30,0.015599,52.992001,0.037043,4.7580,5.285148,35.099083,1156,1.507334,968.100098,0.950000,0.550000,30.021056,-0.942581,27.3600,0.217308,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018789,53.858002,0.002154,4.7170,3.129188,35.120766,0,1.233231,996.539490,1.216667,0.266667,23.736330,-0.779552,27.2450,0.470832,1746.570435,0.653534,0.1210,0.004043,42.349168,8.216,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,30,0.018789,53.937000,0.001265,4.7195,2.233872,35.125887,0,1.233231,1018.213928,1.550000,0.566667,23.736330,-0.779552,27.2500,0.462739,1746.570435,0.653883,0.1115,0.000879,25.914153,8.216,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,30,0.018462,54.015999,0.000377,4.7220,0.179306,35.131008,0,1.233231,1071.519775,1.550000,0.566667,23.285391,-0.784669,27.2600,0.469467,1746.570435,0.654233,0.1020,0.000879,25.914153,8.216,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018270,53.937000,0.002104,4.7220,2.600268,35.174747,0,0.611645,965.657349,1.733333,0.800000,24.659219,-0.792062,27.2550,0.339959,858.381897,0.738552,0.0960,0.000426,20.656527,8.216,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,30,0.016549,53.943001,0.000076,4.7270,0.034857,34.968960,345,0.063687,980.656921,1.550000,0.700000,27.144278,-0.941926,27.2150,0.212634,23.135084,0.234671,0.0620,0.038530,3.044183,8.213,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.7150,0.158397,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.7100,0.224526,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [76]:
grader.check("q8")

q8 results: All test cases passed!

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [79]:
# Filter columns to pH, mean salinity, and depth columns
filtered_data = coral_div[['PH','Salinity_mean','Depth']]

In [82]:
# View the dataframe
filtered_data.head()

       PH  Salinity_mean  Depth
0  8.2175      35.167646   11.0
1  8.2175      35.167646    2.0
2  8.2175      35.167646    4.0
3  8.2175      35.167646    3.0
4  8.2180      35.102688    1.5

In [83]:
grader.check("q9")

q9 results: All test cases passed!

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [ ]:
sampling_2017 = ...

In [ ]:
# View the dataframe 
sampling_2017

In [ ]:
grader.check("q10")

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [ ]:
subset = ...

In [ ]:
# View the dataframe
subset

In [ ]:
grader.check("q11")

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

_Type your answer here, replacing this text._

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [ ]:
subset_na = ...

In [ ]:
# View the dataframe 
subset_na

In [ ]:
grader.check("q14")

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()